### PR TITLE
Cleanup QMLEngine

### PR DESCRIPTION
**Pull request by ChALkeR**
~~Not finished yet.~~

@akreuzkamp, @Plaristote, could you take a quick look at the direction where this is going?

This still needs some comments cleanup and minor code cleanup, which I will doo soon.

### CODE REVIEW

**Comment by ChALkeR** [comment]
@akreuzkamp @Plaristote, could you take a quick look at the direction where this is going?

This still needs some comments cleanup and minor code cleanup, which I will doo soon.

**Comment by akreuzkamp** [comment]
So far it looks good to me. Is there something you'd especially like to hear comments about?

**Comment by ChALkeR** [comment]
@akreuzkamp Nope. Will finish this soon, then.

**Comment by ChALkeR** [comment]
Ok, finished. PTAL.

**Comment by ChALkeR** [comment]
@akreuzkamp, @Plaristote Will merge this today if no objections.

**Comment by Plaristote** [comment]
I'm fine with all the changes, but some conflicts with the master branch have creeped in, it seems.

**Comment by ChALkeR** [comment]
@akreuzkamp This doesn't  have any significant changes since the time you looked afaik, some minor code/comment movement.

@Plaristote The conflict was in the gulpfile (because it had been converted to double quotes), not in the QMLEngine itself. Fixed.

Merging.

**Pull request merged**
