### PR TITLE
QtQuick/MouseArea: Emit positionChanged when pressed & cursor moves outside

### PR DESCRIPTION
**Pull request by stephenmdangelo**
The "mousemove" DOM event is only sent to the MouseArea's DOM element while
the cursor remains over the DOM element. This now attaches a temporary
event listener to "document" and translates the JavaScript MouseEvent
"clientX" and "clientY" properties to the MouseArea's coordinate space
(In regards to CSS transformations, this only takes into account translate
and scale transformations).

### CODE REVIEW

**Comment by stephenmdangelo** [comment]
So this is a little hacky as we have to handle translate/scale transforms manually, but I couldn't find any other cross-browser way to make this work. I've tested this in Safari, Chrome and Firefox.

Firefox has `Element.setCapture` so that even outside of the `MouseArea` DOM element you get `e.offsetX/Y` relative to the `MouseArea` dom element, but Chrome and Safari don't have this.

Safari has `webkitConvertPointFromPageToNode` (https://developer.apple.com/reference/webkitjs/domwindow/1631559-webkitconvertpointfrompagetonode), which would allow us to easily convert `e.pageX/Y` to the `MouseArea` coordinate space (Chrome used to have this, but they removed it in blink with the explanation that `getBoundingClientRect` can be used... except it can't if you have a CSS rotation transformation... there's a hack to position a 1x1 child element at the relative point you want to map and call `getBoundingClientRect`, but that does a local->page mapping, not page->local mapping...).

I briefly looked into positioning 4 1x1 child elements in the corners of the `MouseArea` and mapping each of those and somehow deriving the inverse transformation matrix from that (or going all the way up the DOM tree and combining the parent CSS transform matrices), but that seems like overkill...

End rant. If anyone read this, thank you.

**Comment by stephenmdangelo** [comment]
So I have to investigate a little further, but there may be an issue in Safari.

**Comment by ChALkeR** [comment]
> So I have to investigate a little further, but there may be an issue in Safari.

I added a `work in progress` label for the time being, feel free to remove it when you decide to.

**Comment by ChALkeR** [comment]
@stephenmdangelo This commit looks good to me in its current state. What is the issue in Safari that you were mentioning?

**Comment by stephenmdangelo** [comment]
A colleague of mine was testing it out on a retina MacBook and it seemed like the scale was off (e.g. Stuff wasn't actually following the cursor) I've yet to look into it. We can always merge and fix later? Maybe merging will get some user out there on a retina MacBook to create and issue.

**Comment by ChALkeR** [comment]
I rebased and performed minor style fixes, landing after CI.

**Comment by ChALkeR** [comment]
Landed in 222211cb, thanks!

**Pull request merged**
