### PR TITLE
remove unused file process.js

### PR DESCRIPTION
**Pull request by Plaristote**
While looking at our coverage, I found this file that was not covered at all. I didn't know what it was used for, and after checking, it turns out it's not used... at all.

After removing it, the test still pass (obviously since they didn't cover it), and my own testing apps work the same way as well.
I've looked thoroughly, and haven't found anything in our code that references this file.

I'm not entirely sure what this file was used for. Lpaimen was the only one to have worked with this file, or so it seems.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Don't forget to remove it from `gulpfile.js`.

**Comment by ChALkeR** [comment]
That file was introduced in f7402cf8fd8d7ce3366461fb1f932714f82b2066 by @lpaimen.

**Comment by ChALkeR** [comment]
And perhaps not used anymore after 2cc766fa.

/cc @akreuzkamp

**Comment by ChALkeR** [comment]
LGTM, but I would like to hear from @akreuzkamp here =).

**Comment by ChALkeR** [comment]
This reduces the total lines count of the library by 20%, btw. =)

**Comment by akreuzkamp** [comment]
I'm like 99.973% sure, it's not used and never has been, since I work on qmlweb :) Let's finally get rid of it :)

**Pull request merged**
