### PR TITLE
Add Igor Andruszkiewicz to AUTHORS

### PR DESCRIPTION
**Pull request by ChALkeR**
/cc @igosoft

### CODE REVIEW

**Comment by ChALkeR** [comment]
Ping =)

**Comment by ChALkeR** [comment]
To clarify things: AUTHORS file here consists of everyone who has at least one commit in the master branch.

@igosoft Could you verify that I got your preferred name and email spelled correctly? I've taken that from GitHub.

If everything is correct here, there would be no reasons not to land this.

**Comment by igosoft** [comment]
@ChALkeR it's fine.

**Comment by ChALkeR** [comment]
@igosoft Thanks!

**Pull request merged**
