### PR TITLE
@pavelvasev merge: Support importing code from GitHub

### PR DESCRIPTION
**Pull request by ChALkeR**
This merges cc54d05 and 8cea5b6.

Note: I have not reviewed this code yet, and I am not yet sure if we want it.

Ref: #32.

/cc @pavelvasev @Plaristote @akreuzkamp

### CODE REVIEW

**Comment by Plaristote** [comment]
It's my opinion, but I don't want this. Doesn't sound like something that we should provide ourselves in qmlweb.

**Comment by ChALkeR** [comment]
Perhaps we could replace this with some abstract solution that would support user-supplied path processors for those two methods?

**Comment by ChALkeR** [comment]
I think that I also don't like this in the current state.

**Comment by Plaristote** [comment]
Sounds like the way to go.

We're most likely going to rewrite the better part of the import code anyhow. Perhaps we should just add this to the todo-list for this task (I see we haven't opened an issue on it... but I'm pretty sure I read some of us talking about the import rewrite, we should probably gather what was said there and open an issue... I'll try to find it).

**Comment by ChALkeR** [comment]
@Plaristote I opened #203 for that.

**Pull request closed without merging**
