### PR TITLE
Item width or height set to zero.

### PR DESCRIPTION
**Pull request by igosoft**
Item with width or height set to zero can't rendered.

### CODE REVIEW

**Comment by igosoft** [comment]
@ChALkeR  Please review and merge.

**Comment by ChALkeR** [comment]
@igosoft This fails the tests for whatever reason.
Also, I am not sure about the changes at https://github.com/qmlweb/qmlweb/pull/105/files. Are those all of them? Perhaps you missed something?

**Comment by igosoft** [comment]
@ChALkeR  reverted that one. However I don't understand what/where is failing but I'm sure that width/heigh default values are zero.

**Comment by igosoft** [comment]
@ChALkeR  It probably fails due to NumberAnimation.qml test which as the root component that uses Item which doesn't have background. Am I right ?

**Pull request closed without merging**
