### PR TITLE
MouseArea: Set pressed to false on release, even if outside of MouseArea

### PR DESCRIPTION
**Pull request by stephenmdangelo**
This properly mimics QML's behaviour

@ChALkeR Any ideas on how to test this? From a quick Google search, it looks like we would have to use jQuery event handlers and .trigger to simulate events from within Jasmine, but maybe there's a better way.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Hah, let's just use PhantomJS API for that.

See http://phantomjs.org/page-automation.html and http://phantomjs.org/api/webpage/method/send-event.html.

**Comment by stephenmdangelo** [comment]
So I've pushed what I'm trying, but I can't seem to get the phantom callback called from within my test.  If you could please let me know if I'm on the right track, or if there's a better approach, that would be awesome.

**Comment by ChALkeR** [comment]
@stephenmdangelo You don't want render tests for that, I suppose.

The coordinates `[0, 0]` are wrong — `this.div` is positioned in a different place. I will add a helper function to get that, based on how our `tests/Render/runner.js` currently calculates the area for the screenshot.

Also, not sure what's up with mouse events, but handing them on `window` object works fine. Perhaps some `karma` issues.

**Comment by stephenmdangelo** [comment]
> You don't want render tests for that, I suppose.

Oh, I know. It's just the only place I was able to get `window.top.callPhantom` within the testing scope (I'm assuming because the Render tests have a custom `runner.js`? I'm new to JavaScript testing stuff.)

> I will add a helper function to get that, based on how our `tests/Render/runner.js` currently calculates the area for the screenshot.

Thanks! That would be appreciated. I'll take a look at the code in `runner.js` and see if I can get something working.

> Also, not sure what's up with mouse events, but handing them on `window` object works fine. Perhaps some karma-related issues.

Sorry, not sure what you mean by this? Are you referring to the actual change, or the testing attempts? Is there a testing method other than using PhantomJS's `sendEvent` I could be using?

**Comment by ChALkeR** [comment]
> Sorry, not sure what you mean by this? Are you referring to the actual change, or the testing attempts? Is there a testing method other than using PhantomJS's sendEvent I could be using?

`sendEvent` works with mouse events, and I can listen to them with `window.on{something}`. I have not made a testcase where this actually works with QML code and I'm not sure if there would be any problems there. Everything is running inside a karma enviroment there, there might be frames, different stuff. Try launching `test-debug` and opening it in the browser window, that could help to figure things out.

**Comment by stephenmdangelo** [comment]
I've rebased this and removed my failed attempts at writing a test case.

**Comment by ChALkeR** [comment]
> I've rebased this and removed my failed attempts at writing a test case.

Could you file them separately, please, and mark those as `work-in-progress`, so that we would have a starting point?

LGTM, merging.

**Pull request merged**
