### PR TITLE
gulpfile: rebuild ./lib only if needed

### PR DESCRIPTION
**Pull request by ChALkeR**
This uses `gulp-changed` to achive that.

Will be userful for writing (and testing) tests, because atm it consumes an extra 4 seconds on my notebook on the minification stage.

### CODE REVIEW

**Comment by henrikrudstrom** [comment]
+1

**Comment by ChALkeR** [comment]
@henrikrudstrom How should I mention you in the reviewers list?
`henrikrudstrom <hrudstrom@gmail.com>`? `HenrikRudstrom <hrudstrom@gmail.com>`? `Henrik Rudstrom <hrudstrom@gmail.com>`?

It's the same question as in https://github.com/qmlweb/qmlweb/pull/37#issuecomment-185758735

**Comment by ChALkeR** [comment]
@henrikrudstrom I used `Henrik Rudstrøm <hrudstrom@gmail.com>`.

**Comment by ChALkeR** [comment]
Merged.

**Comment by henrikrudstrom** [comment]
@ChALkeR you picked the one i wanted :)

**Pull request merged**
