### PR TITLE
3 test cases for aliases

### PR DESCRIPTION
**Pull request by pavelvasev**
case 1: alias to id - passing
case 2: alias to id with same name - failing
case 3: alias changed signal - failing
for case 3 see #aliassignals at #32

### CODE REVIEW

**Comment by ChALkeR** [comment]
@pavelvasev Could you rebase against current master, please? There were some problems described in #101, which are now fixed.

**Comment by pavelvasev** [comment]
I just dont understand why travis failing. Seems test api goes forward and backward((((. @henrikrudstrom may you help me?

**Comment by ChALkeR** [comment]
@pavelvasev It was failing because of an inaccurate merge, see #101.
Rebase should help, everything should be fine now.

**Comment by ChALkeR** [comment]
@pavelvasev Ah, in fact not, the test suite was altered, take a look at d96e1ac5eeab9b47e88b24339a328850f71493fd.

**Comment by pavelvasev** [comment]
@ChALkeR I remade these tests 3 times today. :1234:

**Comment by ChALkeR** [comment]
@pavelvasev Will it be ok if I rebase this and force-push here?

**Comment by pavelvasev** [comment]
@ChALkeR I thinked that I already rebased. E.g. I runned some commands from Wiki.. then merged some things from trunk, and pushed.. Now travis shows all is OK. What I missing, may you explain?..

**Comment by ChALkeR** [comment]
@pavelvasev https://github.com/qmlweb/qmlweb/pull/102/commits shows 7 commits instead of one =). And some changes are unrelated and come from other commits that got pulled in.

**Comment by pavelvasev** [comment]
@ChALkeR ohhh.. if you can normalize it, this will be great.. I have no power and actually no knowledge for that.. Thank you in advance!

**Comment by ChALkeR** [comment]
@pavelvasev Done.

LGTM, merging.

**Comment by ChALkeR** [comment]
Status update: those are no longer failing, as of current `master`.

**Pull request merged**
