### PR TITLE
@igosoft merge: Finalize QMLComponent imports

### PR DESCRIPTION
**Pull request by ChALkeR**
This merges commit 46c6f2a023cd14ac2eb097e9dd90e6595b9cb2a6, ref: #223.

The code was significantly changed in rebasing (after e47ff51 and follow-up commits) , but it's still a one-liner.

/cc @igosoft, @akreuzkamp 

PTAL.

### CODE REVIEW

**Comment by ChALkeR** [comment]
@Plaristote, @akreuzkamp 
This is a one-liner, but atm I don't have a complete understanding of how that part is working, so it would be better if someone other than me reviewed this.

**Comment by ChALkeR** [comment]
This shouldn't block 0.1.0 release and cleanups — this is a one-liner change. And someone should take a look at it =).

**Comment by akreuzkamp** [comment]
Unfortunately, I don't know the import code path very well, too.
@Plaristote  
Can you have a look at it? :)

**Comment by ChALkeR** [comment]
Closing in favor of #359.

**Pull request closed without merging**
