### PR TITLE
Add Pavel Vasev to AUTHORS.

### PR DESCRIPTION
**Pull request by ChALkeR**
/cc @pavelvasev 

Also, please leave a comment at #52.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Ping =)

**Comment by pavelvasev** [comment]
Please wait a little for comment #52, I need to read about licenses a little.. Maybe you can point me to some tutorial? Im going to read [this](http://www.gatsbymedia.net/development-articles/why-we-use-the-mpl)

**Comment by pavelvasev** [comment]
@ChALkeR I'm ok with all license options in README ;-)

**Comment by ChALkeR** [comment]
@pavelvasev Does this specific commit (including the name and the email) look good to you? =)

**Comment by pavelvasev** [comment]
@chalker yes

**Comment by ChALkeR** [comment]
@pavelvasev Thanks!
Merging.

**Pull request merged**
