### PR TITLE
QtQuick/MouseArea: set mouseX and mouseY before emitting positionChanged

### PR DESCRIPTION
**Pull request by stephenmdangelo**
This is what Qt QML does.

### CODE REVIEW

**Comment by stephenmdangelo** [comment]
This is a quick test that is different in Qt QML and qmlweb:

```
import QtQuick 2.0

Item {
    MouseArea {
        anchors.fill: parent
        onPositionChanged: {
            console.log(mouse.x, mouse.y, mouseX, mouseY)
        }
    }
}
```

**Comment by stephenmdangelo** [comment]
@ChALkeR Travis seems to be complaining on un-related changes, but only for the first two versions of node?

**Comment by ChALkeR** [comment]
@stephenmdangelo Looks like an eslint update, and it now finds more lint issues. To reproduce: `rm -rf node_modules/eslint*; npm i; npm run lint`.

This is not the fault of this PR, master is failing on lint.

The third Node.js version passes on CI only because it has an older version of eslint cached.

**Comment by ChALkeR** [comment]
@stephenmdangelo Fixed in `master` in 675ec530d3, please rebase =).

**Comment by stephenmdangelo** [comment]
@ChALkeR  Thanks. Rebased.

**Comment by ChALkeR** [comment]
Landed in 02f995127d7b9d4992948e4bd961287aece37fdd, thanks!

**Pull request merged**
