### PR TITLE
Enable eslint for the ./tests folder

### PR DESCRIPTION
**Pull request by ChALkeR**

### CODE REVIEW

**Comment by ChALkeR** [comment]
/cc @Plaristote @akreuzkamp — which format do you prefer? Any considerations? Proposals? Should we discuss some of these rules or should we add some more?

I plan to extend these to all the sources once the merge would be completed (#21).

**Comment by henrikrudstrom** [comment]
@ChALkeR unless anyone has strong opinions here, which it looks like there arent, how about we enable it for the tests now, just to test the linting, we can alway tweak later

**Comment by ChALkeR** [comment]
@henrikrudstrom Should I take that as an «LGTM»?

**Comment by henrikrudstrom** [comment]
LGTM

**Comment by ChALkeR** [comment]
Rebased.
I also fixed lint errors at other places and removed the `no-underscore-dangle` rule, it was broken by the new `Initialize` tests (those have `_version` and `_depends` properties).

**Comment by ChALkeR** [comment]
Landing.

**Pull request merged**
