### PR TITLE
Make tests working.

### LINKED ISSUE #6: Tests are erroring
Something is wrong with the tests, that needs to be investigated.

### PR DESCRIPTION
**Pull request by ChALkeR**
This fixes #6.
/cc @Plaristote 

We need tests coverage, and this is the preliminary step to get those working.

_I plan to add both API tests and render tests in the future, the render tests would take screenshots and compare them to the ones that are known valid. That would work for simple elements, but not for font rendering, I think._

### CODE REVIEW

**Comment by ChALkeR** [comment]
Updated: `gulp-jasmine-phantom@3.0.0-rc1` is released, no need to download from GitHub anymore.

**Comment by Plaristote** [comment]
Looks good. The sooner this is merged, the better. Do we have a process for validating and pulling pull requests ?

**Comment by ChALkeR** [comment]
@Plaristote I'm going to adopt the process from Node.js for now — that means editing all commits to include `Reviewed-by: `,`PR-URL: `, and sometimes `Fixes: ` headers, rebasing, then landing the commits on `master` branch. Will do this now with this PR.

**Comment by ChALkeR** [comment]
@Plaristote Um, seems blocked by #30 =).

**Comment by ChALkeR** [comment]
@Plaristote Do the commit messages mentioning you look good?

**Comment by Plaristote** [comment]
Indeed they do !

**Comment by ChALkeR** [comment]
Thanks, merged!

**Pull request merged**
