### PR TITLE
Remove lib/ dir from the master branch

### PR DESCRIPTION
**Pull request by ChALkeR**
Fixes: https://github.com/qmlweb/qmlweb/issues/27

This removes the `lib/` directory, it will be present only in release tags (option 5 from #27).

Future releases will look like this:
```
* 4efae2b (HEAD -> 0.x) Even more stuff.
| * 9b3977f (tag: v0.3.0) v0.3.0
|/  
* c255e99 Do more stuff
| * 868d255 (tag: v0.2.0) v0.2.0
|/  
* fbd9570 Do stuff
| * 08c6f8b (tag: v0.1.0) v0.1.0
|/ 
```

/cc @qmlweb/core @qmlweb/collaborators 
/cc @Plaristote @henrikrudstrom @aspidites

### CODE REVIEW

**Comment by henrikrudstrom** [comment]
Lets do it!

**Comment by Plaristote** [comment]
Fine by me.

**Comment by aspidites** [comment]
@ChALkeR 

Not to be a party pooper, but a subtle :-1:  from me. Only because it isn't clear from the current readme how to regenerate that lib file. If we could add information to the readme about how to do that, I'd be :+1: . 

Specifically, once the lib directory is gone, the README makes no sense. "Download the file lib/qt.js and preload it in an HTML page." The lib directory, which, after this PR, will no longer exist :-P.

**Comment by ChALkeR** [comment]
@henrikrudstrom How should I mention you in the reviewers list?
`henrikrudstrom <hrudstrom@gmail.com>`?

**Comment by ChALkeR** [comment]
@aspidites, makes sense, thanks! Will update README now.

**Comment by ChALkeR** [comment]
@aspidites PTAL.

**Comment by aspidites** [comment]
Better, but the instructions as written bring us back to a problem stated in #27. Namely, if I download master, then grab qml.js from a release tarball, I'm going to be running a potentially older version of qml.js. What I think we really need, is instructions on how to actually generate the qml.js file.

**Comment by aspidites** [comment]
@ChALkeR, Given my last update, I'm :+1:  on this. I think we can make install instructions clearer in a separate PR.

**Comment by aspidites** [comment]
@ChALkeR I whipped [this](https://github.com/aspidites/qmlweb/tree/update-readme) up to better explain what I am after. I hope that it's now clearer where the lib directory comes from. Thoughts?

**Comment by ChALkeR** [comment]
@aspidites I think that I'm going to merge this as it is now, and improving the Readme further could be done in separate commits. PRs welcome! =)

**Comment by aspidites** [comment]
@ChALkeR,

:+1: , Done  in #44 :-)

**Comment by ChALkeR** [comment]
Merged.

**Pull request merged**
