### PR TITLE
optimize png images

### PR DESCRIPTION
**Pull request by ChALkeR**
This is a lossless operation, actual content is not changed.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Saves 102 bytes on the logo, 400 bytes in tests.
Yes, they were already optimized =). I tuned the parameters a bit.

**Comment by Plaristote** [comment]
LGTM

**Comment by henrikrudstrom** [comment]
LGTM, @ChALkeR what tool are you using to compress, is that something we could put into the qmlweb-dev project?

**Comment by ChALkeR** [comment]
@henrikrudstrom something like this:
```bash
#!/bin/bash
exiftool -overwrite_original -all= "$1";
pngcrush -blacken -brute -reduce -ow -l 9 "$1";
advdef -z -4 "$1";
```

I'm not yet sure if this is optimal, so I'm not certain if this should be the recommended way.

**Pull request merged**
