### PR TITLE
@igosoft patches merge — first batch

### PR DESCRIPTION
**Pull request by ChALkeR**
All of this looks good to me.
Please do not propose further improvements here, open separate issues for them — the intention is to merge `igosoft-patches` in first.

@igosoft, please confirm that everything is ok here, and I will merge this first batch of those changes.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Parent issues: #121, #62.

**Comment by ChALkeR** [comment]
This also solves #90.

**Comment by igosoft** [comment]
I just found one spelling mistake. I left my comment there. Can you please fix it (i don't have access to repo now)

**Comment by ChALkeR** [comment]
@igosoft Done.

**Comment by ChALkeR** [comment]
Is everything else ok?

**Comment by igosoft** [comment]
@ChALkeR Yes. It looks fine.

**Comment by ChALkeR** [comment]
Thanks. LGTM, merging.

**Pull request merged**
