### PR TITLE
Uglybug fix of text input

### PR DESCRIPTION
**Pull request by henrikrudstrom**
fix updateloop for textinput
(659f38103b4b72dc3d74c5dd0183fc0301db4531)

### CODE REVIEW

**Comment by Plaristote** [comment]
I'm fairly certain we've used this kind of behavior in other places.

This LGTM, but I wonder if we shouldn't fix that issue somewhere else (should we really trigger a propertyChanged event if the property has been set to the same value ?).

**Comment by ChALkeR** [comment]
Qt QML does not fire on*Changed signals if the new value is equal to the old value.

**Comment by ChALkeR** [comment]
I'm leaning to rejecting this PR and fixing this in the generic property logic instead.

**Comment by ChALkeR** [comment]
Hm. Signals logic is fine. I'll check what's going on here.

**Comment by ChALkeR** [comment]
Ah, I understand now why and how this happens.
@Plaristote It's not about propertyChanged:
 1. Create a TextInput, type some text into it.
 2. Move cursor to the middle of that text, type something.
 3. The cursor moves to the end of the text.

The signals are fired correctly, see #135, there is only one signal fired when the text is actually changed. But when it's changed, there is a listener that updates the DOM element value, and this one did not check if the current value is already equal to the one that is going to be set, and re-assigned it. It has nothing to do with our signals, it's DOM value updating. And a DOM value update on an input field moves the cursor to the end.

LGTM, merging.

**Pull request merged**
