### PR TITLE
test undefined property

### PR DESCRIPTION
**Pull request by pavelvasev**

### CODE REVIEW

**Comment by ChALkeR** [comment]
Travis failure is unrelated, I restarted it. Blame #109 for that.

**Comment by ChALkeR** [comment]
@pavelvasev What's the actual result here? I mean — what does the property equal to?

**Comment by pavelvasev** [comment]
@ChALkeR the idea is that if property value is not defined, it has the undefined value..

**Comment by ChALkeR** [comment]
@pavelvasev I get that, I was asking what are the actual results atm.
Nevermind, I will check that.

**Comment by ChALkeR** [comment]
Ah, it's `string` for some reason.

LGTM

**Pull request merged**
