### PR TITLE
Merge fork-arnopaehler (e20834e)

### PR DESCRIPTION
**Pull request by Plaristote**
add QMLFont constructor in Checkbox and TextArea
change permitted versions in TextArea
add QMLAnimation constructor in SequentialAnimation

### CODE REVIEW

**Comment by ChALkeR** [comment]
Actual changes LGTM, but I think that there is no need to update `lib/` between releases, I opened #27 to discuss that.

**Comment by Plaristote** [comment]
The question raised with me as well when I was working on these commits.
The lib folder was updated by arnopaehler, so I decided to follow the original committer's approach here. But I do agree that we shouldn't update lib/ on every commit (or even that lib/ shouldn't be in the repository at all).

From the current opinions in #27, for now we all agree that /lib shouldn't be added to every commit. Should I make another pull request in which these commits have been stripped of any changes in /lib ?

**Comment by Plaristote** [comment]
I altered the pull request, removing all changes to the /lib folder.

**Comment by ChALkeR** [comment]
Thanks!
LGTM, merging.

**Pull request merged**
