### PR TITLE
Add Harsh Choudhary to AUTHORS

### PR DESCRIPTION
**Pull request by ChALkeR**
/cc @shry15harsh

### CODE REVIEW

**Comment by akreuzkamp** [comment]
+1

**Comment by ChALkeR** [comment]
To clarify things: AUTHORS file here consists of everyone who has at least one commit in the master branch.

@shry15harsh Could you verify that I got your preferred name and email spelled correctly? I've taken that from GitHub.

If everything is correct here, there would be no reasons not to land this.

**Comment by shry15harsh** [comment]
@ChALkeR Yeah it is alright. :+1: Sorry for replying late.

**Comment by ChALkeR** [comment]
@shry15harsh Thanks!

**Pull request merged**
