### PR TITLE
Checkbox bugfix

### PR DESCRIPTION
**Pull request by henrikrudstrom**
Adds onCheckedChanged

### CODE REVIEW

**Comment by ChALkeR** [comment]
LGTM.

Could you make a testcase for that, btw? It could be done in a separate PR (or this one, as you wish).

**Comment by ChALkeR** [comment]
On the other hand, I would prefer to test this prior to merging.

**Comment by henrikrudstrom** [comment]
i will make a separate PR

**Comment by ChALkeR** [comment]
LGTM, merging.

**Pull request merged**
